const TEAM_NAME_VALUES = {
  '1899_hoffenheim': ['1899 Hoffenheim', 'Hoffenheim'],
  ac_florenz: ['AC Florenz', 'AC Fiorentina', 'Florenz', 'Fiorentina'],
  ac_milan: ['AC Milan', 'Milan'],
  ac_monza: ['AC Monza', 'Monza'],
  aj_auxerre: ['AJ Auxerre', 'Auxerre'],
  ajax_amsterdam: ['Ajax Amsterdam', 'Ajax'],
  albania: ['Albania', 'Albanien'],
  almere_city_fc: ['Almere City FC', 'Almere'],
  apoel_nicosia: ['APOEL Nicosia', 'Apoel Nicosia', 'APOEL'],
  armenia: ['Armenia', 'Armenien'],
  arminia_bielefeld: ['Arminia Bielefeld', 'Bielefeld'],
  arsenal_fc: ['Arsenal FC', 'Arsenal'],
  as_monaco: ['AS Monaco', 'Monaco'],
  as_rom: ['AS Rom', 'AS Roma'],
  aston_villa: ['Aston Villa'],
  atalanta_bergamo: ['Atalanta Bergamo', 'Atalanta'],
  athletic_club: ['Athletic Club', 'Athletic Bilbao', 'Bilbao'],
  atlanta_united_fc: ['Atlanta United FC', 'Atlanta'],
  atletico_madrid: ['Atletico Madrid', 'Atlético Madrid', 'Atlético'],
  austin_fc: ['Austin FC', 'Austin'],
  austria: ['Austria', 'Österreich'],
  az_alkmaar: ['AZ Alkmaar', 'Alkmaar'],
  azerbaijan: ['Azerbaijan', 'Aserbaidschan'],
  backa_topola: ['Backa Topola', 'TSC Backa Topola'],
  bayer_leverkusen: ['Bayer Leverkusen', 'Bayer 04 Leverkusen', 'Leverkusen'],
  bayern_munich: [
    'Bayern Munich',
    'Bayern München',
    'FC Bayern München',
    'Bayern',
  ],
  belgien: ['Belgien', 'Belgium'],
  bologna_fc_1909: ['Bologna FC 1909', 'Bologna'],
  borac_banja_luka: ['Borac Banja Luka', 'FK Borac Banja Luka', 'Borac'],
  borussia_dortmund: ['Borussia Dortmund', 'Dortmund'],
  borussia_hildesheim: ['Borussia Hildesheim', 'Hildesheim'],
  borussia_monchengladbach: [
    'Borussia Monchengladbach',
    'Borussia Mönchengladbach',
    "M'Gladbach",
  ],
  bosnia_herzegovina: [
    'Bosnia & Herzegovina',
    'Bosnien',
    'Bosnien-Herzegowina',
  ],
  botev_plovdiv: ['Botev Plovdiv', 'PFK Botew Plowdiw', 'Botev'],
  brighton_hove_albion: ['Brighton & Hove Albion', 'Brighton'],
  bulgaria: ['Bulgaria', 'Bulgarien'],
  burnley: ['Burnley'],
  ca_osasuna: ['CA Osasuna', 'Osasuna'],
  cadiz_cf: ['Cádiz CF', 'Cadiz', 'Cádiz'],
  cagliari_calcio: ['Cagliari Calcio', 'Cagliari'],
  cd_leganes: ['CD Leganés', 'Leganes', 'Leganés'],
  celtic_glasgow: ['Celtic Glasgow', 'Celtic'],
  cf_montreal: ['CF Montreal', 'Montreal'],
  cfc_genua: ['CFC Genua', 'Genoa', 'Genua'],
  charlotte_fc: ['Charlotte FC', 'Charlotte'],
  chelsea_fc: ['Chelsea FC', 'Chelsea'],
  chicago_fire: ['Chicago Fire', 'Chicago Fire FC'],
  chigago_fire: ['Chigago Fire', 'Chicago'],
  clermont_foot: ['Clermont Foot', 'Clermont'],
  club_brugge_kv: ['Club Brugge KV', 'Brügge'],
  colorado_rapids: ['Colorado Rapids', 'Rapids'],
  columbus_crew: ['Columbus Crew', 'Columbus'],
  como_1907: ['Como 1907', 'Como'],
  corvinul_hunedoara: [
    'Corvinul Hunedoara',
    'CS Corvinul 1921 Hunedoara',
    'Corvinul',
  ],
  croatia: ['Croatia', 'Kroatien'],
  crystal_palace: ['Crystal Palace', 'Crystal'],
  cyprus: ['Cyprus', 'Zypern'],
  cz_jena: ['CZ Jena', 'FC Carl Zeiss Jena'],
  czech_republic: ['Czech Republic', 'Tschechien'],
  dc_united: ['DC United', 'Washington D.C. United'],
  denmark: ['Denmark', 'Dänemark'],
  deportivo_alaves: ['Deportivo Alavés', 'Alaves'],
  dinamo_batumi: ['Dinamo Batumi', 'FC Dinamo Batumi', 'Batumi'],
  dinamo_minsk: ['Dinamo Minsk', 'FK Dinamo Minsk', 'Minsk'],
  dynamo_dresden: ['Dynamo Dresden', 'Dresden'],
  dynamo_kiew: ['Dynamo Kiew', 'Dynamo Kyiv', 'FK Dynamo Kiew'],
  egnatia_rrogozhine: [
    'Egnatia Rrogozhinë',
    'KS Egnatia Rrogozhinë',
    'Egnatia',
  ],
  eintracht_braunschweig: ['Eintracht Braunschweig', 'Braunschweig'],
  eintracht_frankfurt: ['Eintracht Frankfurt', 'Frankfurt'],
  empoli_fc: ['Empoli FC', 'Empoli'],
  estland: ['Estland', 'Estonia'],
  everton: ['Everton'],
  faroe_islands: ['Faroe Islands', 'Färöer'],
  fc_augsburg: ['FC Augsburg', 'Augsburg'],
  fc_barcelona: ['FC Barcelona', 'Barcelona'],
  fc_cincinnati: ['FC Cincinnati', 'Cincinnati'],
  fc_dallas: ['FC Dallas', 'Dallas'],
  fc_differdange_03: ['FC Differdange 03', 'Differdange'],
  fc_heidenheim: [
    'FC Heidenheim',
    '1.FC Heidenheim',
    '1. FC Heidenheim',
    'Heidenheim',
  ],
  fc_ingolstadt_04: ['FC Ingolstadt 04', 'Ingolstadt'],
  fc_kaiserslautern: [
    'FC Kaiserslautern',
    '1. FC Kaiserslautern',
    'Kaiserslautern',
  ],
  fc_koln: ['FC Koln', '1.FC Köln', '1. FC Köln', 'Köln'],
  fc_lorient: ['FC Lorient', 'Lorient'],
  fc_magdeburg: ['FC Magdeburg', '1. FC Magdeburg', 'Magdeburg'],
  fc_metz: ['FC Metz', 'Metz'],
  fc_midtjylland: ['FC Midtjylland', 'Midtjylland'],
  fc_nantes: ['FC Nantes', 'Nantes'],
  fc_nurnberg: ['FC Nurnberg', 'FC Nürnberg', '1. FC Nürnberg', 'Nürnberg'],
  fc_petrocub_hincesti: ['FC Petrocub-Hîncesti', 'Petrocub'],
  fc_porto: ['FC Porto', 'Porto'],
  fc_saarbrucken: ['FC Saarbrücken', 'Saarbrücken'],
  fc_schalke_04: ['FC Schalke 04', 'Schalke'],
  fc_sevilla: ['FC Sevilla', 'Sevilla'],
  fc_struga: ['FC Struga', 'Struga'],
  fc_toulouse: ['FC Toulouse', 'Toulouse'],
  fc_valencia: ['FC Valencia', 'Valencia'],
  fcsb_bukarest: ['FCSB Bukarest', 'FCSB'],
  ferencvarosi_tc: ['Ferencvarosi TC', 'Ferencváros Budapest', 'Ferencvárosi'],
  feyenoord_rotterdam: ['Feyenoord Rotterdam', 'Feyenoord'],
  finland: ['Finland', 'Finnland'],
  fk_bod_glimt: ['FK Bodø/Glimt', 'Bodo/Glimt', 'Bodø/Glimt'],
  fk_decic_tuzi: ['FK Dečić Tuzi', 'Dečić'],
  fk_ordabassy_schymkent: ['FK Ordabassy Schymkent', 'Ordabasy', 'Ordabassy'],
  fk_panevezys: ['FK Panevėžys', 'Panevėžys'],
  fk_tobol_kostanay: ['FK Tobol Kostanay', 'FK Tobyl Qostanai', 'Tobol'],
  flora_tallinn: ['Flora Tallinn', 'FC Flora Tallinn', 'Flora'],
  fortuna_dusseldorf: [
    'Fortuna Dusseldorf',
    'Fortuna Düsseldorf',
    'Düsseldorf',
  ],
  fortuna_sittard: ['Fortuna Sittard', 'Sittard'],
  france: ['France', 'Frankreich'],
  frosinone_calcio: ['Frosinone Calcio', 'Frosinone'],
  fsv_mainz_05: ['FSV Mainz 05', 'Mainz'],
  fulham: ['Fulham'],
  fyr_macedonia: ['FYR Macedonia', 'Nordmazedonien'],
  ga_eagles: ['GA Eagles', 'GO Ahead Eagles', 'Go Ahead Eagles'],
  galatasaray_istanbul: ['Galatasaray Istanbul', 'Galatasaray'],
  georgia: ['Georgia', 'Georgien'],
  germany: ['Germany', 'Deutschland'],
  getafe_cf: ['Getafe CF', 'Getafe'],
  girona_fc: ['Girona FC', 'Girona'],
  granada_cf: ['Granada CF', 'Granada'],
  greece: ['Greece', 'Griechenland'],
  greifswalder_fc: ['Greifswalder FC', 'Greifswald'],
  hamburger_sv: ['Hamburger SV', 'Hamburg'],
  hamrun_spartans: ['Hamrun Spartans', 'Ħamrun Spartans', 'Ħamrun'],
  hannover_96: ['Hannover 96', 'Hannover'],
  hansa_rostock: ['Hansa Rostock', 'Rostock'],
  heart_of_midlothian: ['Heart Of Midlothian', 'Hearts'],
  hellas_verona: ['Hellas Verona', 'Verona'],
  heracles_almelo: ['Heracles Almelo', 'Heracles'],
  hertha_bsc: ['Hertha BSC', 'Hertha Berlin', 'Hertha'],
  hjk_helsinki: ['HJK Helsinki', 'HJK helsinki', 'Helsinki'],
  holstein_kiel: ['Holstein Kiel', 'Kiel'],
  houston_dynamo: ['Houston Dynamo', 'Houston'],
  if_elfsborg: ['IF Elfsborg', 'IF elfsborg', 'Elfsborg'],
  inter_mailand: ['Inter Mailand', 'Inter'],
  island: ['Island', 'Iceland'],
  italy: ['Italy', 'Italien'],
  jahn_regensburg: ['Jahn Regensburg', 'SSV Jahn Regensburg', 'Regensburg'],
  juventus_turin: ['Juventus Turin', 'Juventus'],
  karlsruher_sc: ['Karlsruher SC', 'Karlsruhe'],
  kasachstan: ['Kasachstan', 'Kazakhstan'],
  kf_ballkani: ['KF Ballkani', 'Ballkani'],
  kf_llapi_podujeve: ['KF Llapi Podujevë', 'Llapi'],
  ki_klaksvik: ['KI Klaksvik', 'KÍ Klaksvík', 'Klaksvík'],
  kickers_offenbach: ['Kickers Offenbach', 'Offenbach'],
  la_galaxy: ['LA Galaxy', 'Los Angeles Galaxy'],
  larne_fc: ['Larne FC', 'Larne'],
  las_palmas: ['Las Palmas', 'UD Las Palmas'],
  latvia: ['Latvia', 'Lettland'],
  lazio_rom: ['Lazio Rom', 'Lazio'],
  le_havre: ['LE Havre', 'Le Havre', 'Le Havre AC'],
  leeds_united: ['Leeds United'],
  levante_ud: ['Levante UD', 'Levante'],
  lille_olympique_sporting_club: ['Lille Olympique Sporting Club', 'Lille'],
  lincoln_red_imps_fc: ['Lincoln Red Imps FC', 'Lincoln'],
  litauen: ['Litauen', 'Lithuania'],
  liverpool_fc: ['Liverpool FC', 'Liverpool'],
  los_angeles_fc: ['Los Angeles FC', 'LAFC'],
  ludogorez_rasgrad: ['Ludogorez Rasgrad', 'Ludogorez'],
  luton_town: ['Luton Town', 'Luton'],
  luxemburg: ['Luxemburg', 'Luxembourg'],
  maccabi_tel_aviv: ['Maccabi Tel Aviv', 'Maccabi'],
  malmo_ff: ['Malmo FF', 'Malmö FF', 'Malmö'],
  man_city: ['Man City', 'Manchester City'],
  man_united: ['Man United', 'Manchester United'],
  mfk_ruzomberok: ['MFK Ružomberok', 'Ružomberok'],
  minnesota_united_fc: ['Minnesota United FC', 'Minnesota'],
  molde_fk: ['Molde FK', 'Molde'],
  moldova: ['Moldova', 'Moldawien'],
  montpellier_hsc: ['Montpellier HSC', 'Montpellier'],
  nashville_sc: ['Nashville SC', 'Nashville'],
  nec_nijmegen: ['NEC Nijmegen', 'Nijmegen'],
  netherlands: ['Netherlands', 'Niederlande'],
  new_england: ['New England', 'New England Revolution'],
  new_york_fc: ['New York FC', 'New York City FC'],
  new_york_rb: ['New York RB', 'New York Red Bulls'],
  nk_celje: ['NK Celje', 'Celje'],
  nk_maribor: ['NK Maribor', 'Maribor'],
  northern_ireland: ['Northern Ireland', 'Nordirland'],
  norway: ['Norway', 'Norwegen'],
  nottingham_forest: ['Nottingham Forest', 'Nottingham'],
  ogc_nizza: ['OGC Nizza', 'Nice'],
  olympiakos_piraeus: ['Olympiakos Piraeus', 'Olympiakos'],
  olympique_de_marseille: ['Olympique de Marseille', 'Marseille'],
  olympique_lyonnais: ['Olympique Lyonnais', 'Lyon'],
  orlando_city_sc: ['Orlando City SC', 'Orlando'],
  paksi_fc: ['Paksi FC', 'Paks'],
  paok_thessaloniki: ['PAOK Thessaloniki', 'PAOK'],
  paphos_fc: ['Paphos FC', 'Pafos'],
  paris_sg: ['Paris SG', 'Paris Saint Germain', 'Paris Saint-Germain'],
  parma_calcio_1913: ['Parma Calcio 1913', 'Parma'],
  philadelphia_union: ['Philadelphia Union', 'Philadelphia'],
  polen: ['Polen', 'Poland'],
  portland_timbers: ['Portland Timbers', 'Portland'],
  preu_en_munster: [
    'Preußen Münster',
    'Preussen Munster',
    'Preussen Münster',
    'Münster',
  ],
  psv_eindhoven: ['PSV Eindhoven', 'Eindhoven'],
  pyunik_yerevan: ['Pyunik Yerevan', 'FC Pyunik Yerevan', 'Pyunik'],
  racing_club_de_strasbourg: ['Racing Club de Strasbourg', 'Strasbourg'],
  rayo_vallecano: ['Rayo Vallecano', 'Rayo Vallecano de Madrid', 'Vallecano'],
  rb_salzburg: ['RB Salzburg', 'Red Bull Salzburg'],
  rc_lens: ['RC Lens', 'Racing Club de Lens', 'Lens'],
  rcd_espanyol_barcelona: ['RCD Espanyol Barcelona', 'Espanyol'],
  rcd_mallorca: ['RCD Mallorca', 'Mallorca'],
  real_betis: ['Real Betis', 'Real Betis Sevilla'],
  real_madrid: ['Real Madrid', 'Real Madrid CF'],
  real_sociedad: ['Real Sociedad', 'Real Sociedad San Sebastián', 'Sociedad'],
  real_valladolid: ['Real Valladolid', 'Valladolid'],
  rep_of_ireland: ['Rep. Of Ireland', 'Irland'],
  rigas_fs: ['Rīgas FS', 'Rīgas'],
  rkc_waalwijk: ['RKC Waalwijk', 'Waalwijk'],
  romania: ['Romania', 'Rumänien'],
  roter_stern: ['Roter Stern', 'FK Crvena Zvezda', 'FK Roter Stern Belgrad'],
  rw_essen: ['RW Essen', 'Rot-Weiß Essen'],
  saint_etienne: [
    'Saint Etienne',
    'AS Saint-Étienne',
    'St-Étienne',
    'Saint-Etienne',
  ],
  san_diego: ['San Diego', 'San Diego FC'],
  san_jose_earthquakes: [
    'San Jose Earthquakes',
    'San José Earthquakes',
    'Earthquakes',
  ],
  sc_braga: ['SC Braga', 'Braga'],
  sc_freiburg: ['SC Freiburg', 'Freiburg'],
  sc_paderborn_07: ['SC Paderborn 07', 'Paderborn'],
  schachtar_donezk: ['Schachtar Donezk', 'Shakhtar Donetsk', 'Shakhtar'],
  schweiz: ['Schweiz', 'Switzerland'],
  sco_angers: ['SCO Angers', 'Angers'],
  scotland: ['Scotland', 'Schottland'],
  seattle_sounders: ['Seattle Sounders', 'Seattle'],
  serbia: ['Serbia', 'Serbien'],
  shamrock_rovers: ['Shamrock Rovers', 'Shamrock'],
  sheffield_utd: ['Sheffield Utd', 'Sheffield United'],
  sheriff_tiraspol: ['Sheriff Tiraspol', 'Sheriff'],
  sk_rapid: ['SK Rapid', 'Rapid Vienna', 'Sportklub Rapid Wien'],
  sl_benfica: ['SL Benfica', 'Benfica'],
  slavia_prag: ['Slavia Prag', 'Slavia Praha', 'Sparta Praha', 'Prag'],
  slovakia: ['Slovakia', 'Slowakei'],
  slovan_bratislava: [
    'Slovan Bratislava',
    'ŠK Slovan Bratislava',
    'Bratislava',
  ],
  slovenia: ['Slovenia', 'Slowenien'],
  southampton: ['Southampton'],
  spain: ['Spain', 'Spanien'],
  sparta_rotterdam: ['Sparta Rotterdam', 'Rotterdam'],
  sportfreunde_lotte: ['Sportfreunde Lotte', 'Lotte'],
  sporting_cp: ['Sporting CP', 'Sporting Clube de Portugal', 'Sporting'],
  sporting_kc: ['Sporting KC', 'Sporting Kansas City'],
  spvgg_greuter_furth: ['SpVgg Greuter Furth', 'SpVgg Greuter Fürth'],
  spvgg_greuther_furth: [
    'SpVgg Greuther Furth',
    'SpVgg Greuther Fürth',
    'Fürth',
  ],
  ss_virtus: ['SS Virtus', 'Virtus'],
  ssc_napoli: ['SSC Napoli', 'Napoli', 'Neapel'],
  ssv_ulm_1846: ['SSV ULM 1846', 'SSV Ulm 1846', 'Ulm'],
  st_gilloise: ['St. Gilloise', 'Union St. Gilloise'],
  st_louis: ['St. Louis', 'St. Louis City', 'St. Louis City SC'],
  st_pauli: ['St. Pauli', 'FC St. Pauli'],
  stade_brestois_29: ['Stade Brestois 29', 'Brest'],
  stade_de_reims: ['Stade de Reims', 'Reims'],
  stade_rennais_fc: ['Stade Rennais FC', 'Rennes'],
  sturm_graz: ['Sturm Graz', 'SK Sturm Graz'],
  sv_darmstadt_98: ['SV Darmstadt 98', 'Darmstadt'],
  sv_elversberg: ['SV Elversberg', 'Elversberg'],
  sv_meppen: ['SV Meppen', 'Meppen'],
  sv_sandhausen: ['SV Sandhausen', 'Sandhausen'],
  sweden: ['Sweden', 'Schweden'],
  teutonia_ottensen: ['Teutonia Ottensen', 'Ottensen'],
  the_new_saints: ['The New Saints', 'The New Saints FC', 'Saints'],
  torino_fc: ['Torino FC', 'Turin', 'Torino'],
  tottenham_hotspur: ['Tottenham Hotspur', 'Spurs', 'Tottenham'],
  turkei: ['Türkei', 'Türkiye'],
  tus_koblenz: ['TuS Koblenz', 'Koblenz'],
  ud_almeria: ['UD Almería', 'Almeria', 'Almería'],
  udinese_calcio: ['Udinese Calcio', 'Udinese'],
  ue_santa_coloma: ['UE Santa Coloma', 'Coloma'],
  ungarn: ['Ungarn', 'Hungary'],
  union_berlin: ['Union Berlin', 'Union'],
  us_lecce: ['US Lecce', 'Lecce'],
  us_salernitana: ['US Salernitana', 'Salernitana'],
  us_sassuolo: ['US Sassuolo', 'Sassuolo'],
  vancouver_whitecaps: [
    'Vancouver Whitecaps',
    'Vancouver Whitecaps FC',
    'Whitecaps',
  ],
  venezia_fc: ['Venezia FC', 'Venedig', 'Venezia'],
  vfb_stuttgart: ['VfB Stuttgart', 'Stuttgart'],
  vfl_bochum: ['VfL Bochum', 'Vfl Bochum', 'Bochum'],
  vfl_wolfsburg: ['VfL Wolfsburg', 'Wolfsburg'],
  vfr_aalen: ['VfR Aalen', 'Aalen'],
  vikingur_reykjavik: ['Vikingur Reykjavik', 'Víkingur Reykjavík', 'Víkingur'],
  viktoria_pilsen: ['Viktoria Pilsen', 'FC Viktoria Pilsen', 'Plzen'],
  villarreal_cf: ['Villarreal CF', 'Villarreal'],
  werder_bremen: ['Werder Bremen', 'Bremen'],
  west_ham: ['West Ham', 'West Ham United'],
  wisla_krakow: ['Wisla Krakow', 'Wisła Kraków', 'Wisła'],
  wolverhampton_wanderers: ['Wolverhampton Wanderers', 'Wolves'],
  wurzburger_k: ['Würzburger K.', 'Würzburger Kickers'],
  young_boys: ['Young Boys', 'BSC Young Boys'],
  zir_fk: ['Zirə FK', 'Zira', 'Zirə'],
} as const;

type TeamNameKey = keyof typeof TEAM_NAME_VALUES;

export const TEAM_NAME_SEARCH_VALUES: Record<TeamNameKey, readonly string[]> =
  TEAM_NAME_VALUES;
