sonar.sources=apps,lib
sonar.tests=apps,lib
sonar.python.version=3.9
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts
sonar.cpd.exclusions=apps/client/src/testing/standings.mock.ts
sonar.javascript.lcov.reportPaths=coverage/apps/api/lcov.info,coverage/apps/client/lcov.info,coverage/lib/lcov.info
