import { LeagueStanding } from '../../models';
import { COMPETITION_LABEL } from '../competition/label.constant';

export const LEAGUE_STANDING_EXAMPLES: LeagueStanding[] = [
  {
    competition: COMPETITION_LABEL.GERMANY_BUNDESLIGA,
    list: [
      {
        rank: 1,
        team: 'FC Bayern München',
        played: 34,
        won: 24,
        draw: 6,
        lost: 4,
        goalsFor: 99,
        goalsAgainst: 44,
        goalDifference: 55,
        points: 78,
      },
      {
        rank: 2,
        team: 'RB Leipzig',
        played: 34,
        won: 21,
        draw: 8,
        lost: 5,
        goalsFor: 60,
        goalsAgainst: 25,
        goalDifference: 35,
        points: 71,
      },
      {
        rank: 3,
        team: 'Borussia Dortmund',
        played: 34,
        won: 21,
        draw: 6,
        lost: 7,
        goalsFor: 84,
        goalsAgainst: 41,
        goalDifference: 43,
        points: 69,
      },
      {
        rank: 4,
        team: 'Borussia Mönchengladbach',
        played: 34,
        won: 20,
        draw: 5,
        lost: 9,
        goalsFor: 66,
        goalsAgainst: 40,
        goalDifference: 26,
        points: 65,
      },
      {
        rank: 5,
        team: 'Bayer 04 Leverkusen',
        played: 34,
        won: 19,
        draw: 6,
        lost: 9,
        goalsFor: 61,
        goalsAgainst: 44,
        goalDifference: 17,
        points: 63,
      },
      {
        rank: 6,
        team: 'VfL Wolfsburg',
        played: 34,
        won: 17,
        draw: 10,
        lost: 7,
        goalsFor: 62,
        goalsAgainst: 46,
        goalDifference: 16,
        points: 61,
      },
      {
        rank: 7,
        team: 'SC Freiburg',
        played: 34,
        won: 13,
        draw: 9,
        lost: 12,
        goalsFor: 48,
        goalsAgainst: 47,
        goalDifference: 1,
        points: 48,
      },
      {
        rank: 8,
        team: 'Eintracht Frankfurt',
        played: 34,
        won: 13,
        draw: 6,
        lost: 15,
        goalsFor: 59,
        goalsAgainst: 60,
        goalDifference: -1,
        points: 45,
      },
      {
        rank: 9,
        team: 'Hertha BSC',
        played: 34,
        won: 11,
        draw: 8,
        lost: 15,
        goalsFor: 48,
        goalsAgainst: 59,
        goalDifference: -11,
        points: 41,
      },
      {
        rank: 10,
        team: '1. FC Köln',
        played: 34,
        won: 11,
        draw: 8,
        lost: 15,
        goalsFor: 48,
        goalsAgainst: 63,
        goalDifference: -15,
        points: 41,
      },
      {
        rank: 11,
        team: 'FC Schalke 04',
        played: 34,
        won: 9,
        draw: 12,
        lost: 13,
        goalsFor: 38,
        goalsAgainst: 58,
        goalDifference: -20,
        points: 39,
      },
      {
        rank: 12,
        team: '1. FC Union Berlin',
        played: 34,
        won: 12,
        draw: 5,
        lost: 17,
        goalsFor: 41,
        goalsAgainst: 58,
        goalDifference: -17,
        points: 41,
      },
      {
        rank: 13,
        team: 'FSV Mainz 05',
        played: 34,
        won: 11,
        draw: 4,
        lost: 19,
        goalsFor: 44,
        goalsAgainst: 65,
        goalDifference: -21,
        points: 37,
      },
      {
        rank: 14,
        team: 'FC Augsburg',
        played: 34,
        won: 9,
        draw: 9,
        lost: 16,
        goalsFor: 36,
        goalsAgainst: 54,
        goalDifference: -18,
        points: 36,
      },
      {
        rank: 15,
        team: '1. FSV Mainz 05',
        played: 34,
        won: 10,
        draw: 6,
        lost: 18,
        goalsFor: 34,
        goalsAgainst: 58,
        goalDifference: -24,
        points: 36,
      },
      {
        rank: 16,
        team: 'Fortuna Düsseldorf',
        played: 34,
        won: 6,
        draw: 12,
        lost: 16,
        goalsFor: 36,
        goalsAgainst: 67,
        goalDifference: -31,
        points: 30,
      },
      {
        rank: 17,
        team: 'Werder Bremen',
        played: 34,
        won: 8,
        draw: 7,
        lost: 19,
        goalsFor: 42,
        goalsAgainst: 69,
        goalDifference: -27,
        points: 31,
      },
      {
        rank: 18,
        team: 'SC Paderborn 07',
        played: 34,
        won: 4,
        draw: 8,
        lost: 22,
        goalsFor: 37,
        goalsAgainst: 74,
        goalDifference: -37,
        points: 20,
      },
    ],
  },
  {
    competition: COMPETITION_LABEL.FRANCE_LIGUE_1,
    list: [
      {
        rank: 1,
        team: 'Paris Saint-Germain',
        played: 38,
        won: 26,
        draw: 8,
        lost: 4,
        goalsFor: 86,
        goalsAgainst: 28,
        goalDifference: 58,
        points: 86,
      },
      {
        rank: 2,
        team: 'Olympique de Marseille',
        played: 38,
        won: 21,
        draw: 7,
        lost: 10,
        goalsFor: 60,
        goalsAgainst: 41,
        goalDifference: 19,
        points: 70,
      },
      {
        rank: 3,
        team: 'Stade Rennais FC',
        played: 38,
        won: 18,
        draw: 10,
        lost: 10,
        goalsFor: 72,
        goalsAgainst: 44,
        goalDifference: 28,
        points: 64,
      },
      {
        rank: 4,
        team: 'LOSC Lille',
        played: 38,
        won: 17,
        draw: 11,
        lost: 10,
        goalsFor: 62,
        goalsAgainst: 44,
        goalDifference: 18,
        points: 62,
      },
      {
        rank: 5,
        team: 'Olympique Lyonnais',
        played: 38,
        won: 17,
        draw: 9,
        lost: 12,
        goalsFor: 60,
        goalsAgainst: 43,
        goalDifference: 17,
        points: 60,
      },
      {
        rank: 6,
        team: 'AS Monaco',
        played: 38,
        won: 17,
        draw: 7,
        lost: 14,
        goalsFor: 60,
        goalsAgainst: 44,
        goalDifference: 16,
        points: 58,
      },
    ],
  },
];
