import type { StandingsDTO } from '@lib/models';

export const EXAMPLE_STANDINGS: StandingsDTO = {
  _id: '6a86ce1686fd3afa624fd1e4',
  league: {
    id: 140,
    name: 'La Liga',
    country: 'Spain',
    logo: 'https://media.api-sports.io/football/leagues/140.png',
    flag: 'https://media.api-sports.io/flags/es.svg',
    season: 2026,
    standings: [
      [
        {
          rank: 1,
          team: {
            id: 540,
            name: 'Espanyol',
            logo: 'https://media.api-sports.io/football/teams/540.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 2,
          team: {
            id: 542,
            name: 'Alaves',
            logo: 'https://media.api-sports.io/football/teams/542.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 3,
          team: {
            id: 530,
            name: 'Atletico Madrid',
            logo: 'https://media.api-sports.io/football/teams/530.png',
          },
          points: 3,
          goalsDiff: 2,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 4,
          team: {
            id: 536,
            name: 'Sevilla',
            logo: 'https://media.api-sports.io/football/teams/536.png',
          },
          points: 3,
          goalsDiff: 1,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 5,
          team: {
            id: 4665,
            name: 'Racing Santander',
            logo: 'https://media.api-sports.io/football/teams/4665.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'Europa League league stage',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 6,
          team: {
            id: 533,
            name: 'Villarreal',
            logo: 'https://media.api-sports.io/football/teams/533.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'ECL Playoffs',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 7,
          team: {
            id: 797,
            name: 'Elche',
            logo: 'https://media.api-sports.io/football/teams/797.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 8,
          team: {
            id: 544,
            name: 'Deportivo La Coruna',
            logo: 'https://media.api-sports.io/football/teams/544.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 9,
          team: {
            id: 529,
            name: 'Barcelona',
            logo: 'https://media.api-sports.io/football/teams/529.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 10,
          team: {
            id: 541,
            name: 'Real Madrid',
            logo: 'https://media.api-sports.io/football/teams/541.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 11,
          team: {
            id: 543,
            name: 'Real Betis',
            logo: 'https://media.api-sports.io/football/teams/543.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 12,
          team: {
            id: 538,
            name: 'Celta Vigo',
            logo: 'https://media.api-sports.io/football/teams/538.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 13,
          team: {
            id: 532,
            name: 'Valencia',
            logo: 'https://media.api-sports.io/football/teams/532.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 14,
          team: {
            id: 548,
            name: 'Real Sociedad',
            logo: 'https://media.api-sports.io/football/teams/548.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 15,
          team: {
            id: 531,
            name: 'Athletic Club',
            logo: 'https://media.api-sports.io/football/teams/531.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 16,
          team: {
            id: 727,
            name: 'Osasuna',
            logo: 'https://media.api-sports.io/football/teams/727.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 17,
          team: {
            id: 728,
            name: 'Rayo Vallecano',
            logo: 'https://media.api-sports.io/football/teams/728.png',
          },
          points: 0,
          goalsDiff: -1,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 18,
          team: {
            id: 535,
            name: 'Malaga',
            logo: 'https://media.api-sports.io/football/teams/535.png',
          },
          points: 0,
          goalsDiff: -2,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 19,
          team: {
            id: 539,
            name: 'Levante',
            logo: 'https://media.api-sports.io/football/teams/539.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 20,
          team: {
            id: 546,
            name: 'Getafe',
            logo: 'https://media.api-sports.io/football/teams/546.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
      ],
      [
        {
          rank: 1,
          team: {
            id: 542,
            name: 'Alaves',
            logo: 'https://media.api-sports.io/football/teams/542.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 2,
          team: {
            id: 540,
            name: 'Espanyol',
            logo: 'https://media.api-sports.io/football/teams/540.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 3,
          team: {
            id: 530,
            name: 'Atletico Madrid',
            logo: 'https://media.api-sports.io/football/teams/530.png',
          },
          points: 3,
          goalsDiff: 2,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 4,
          team: {
            id: 536,
            name: 'Sevilla',
            logo: 'https://media.api-sports.io/football/teams/536.png',
          },
          points: 3,
          goalsDiff: 1,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 5,
          team: {
            id: 4665,
            name: 'Racing Santander',
            logo: 'https://media.api-sports.io/football/teams/4665.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'Europa League league stage',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 6,
          team: {
            id: 544,
            name: 'Deportivo La Coruna',
            logo: 'https://media.api-sports.io/football/teams/544.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 7,
          team: {
            id: 531,
            name: 'Athletic Club',
            logo: 'https://media.api-sports.io/football/teams/531.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 8,
          team: {
            id: 529,
            name: 'Barcelona',
            logo: 'https://media.api-sports.io/football/teams/529.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 9,
          team: {
            id: 538,
            name: 'Celta Vigo',
            logo: 'https://media.api-sports.io/football/teams/538.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 10,
          team: {
            id: 797,
            name: 'Elche',
            logo: 'https://media.api-sports.io/football/teams/797.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 11,
          team: {
            id: 546,
            name: 'Getafe',
            logo: 'https://media.api-sports.io/football/teams/546.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 12,
          team: {
            id: 539,
            name: 'Levante',
            logo: 'https://media.api-sports.io/football/teams/539.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 13,
          team: {
            id: 535,
            name: 'Malaga',
            logo: 'https://media.api-sports.io/football/teams/535.png',
          },
          points: 0,
          goalsDiff: -2,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 14,
          team: {
            id: 727,
            name: 'Osasuna',
            logo: 'https://media.api-sports.io/football/teams/727.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 15,
          team: {
            id: 728,
            name: 'Rayo Vallecano',
            logo: 'https://media.api-sports.io/football/teams/728.png',
          },
          points: 0,
          goalsDiff: -1,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 16,
          team: {
            id: 543,
            name: 'Real Betis',
            logo: 'https://media.api-sports.io/football/teams/543.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 17,
          team: {
            id: 541,
            name: 'Real Madrid',
            logo: 'https://media.api-sports.io/football/teams/541.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 18,
          team: {
            id: 548,
            name: 'Real Sociedad',
            logo: 'https://media.api-sports.io/football/teams/548.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 19,
          team: {
            id: 532,
            name: 'Valencia',
            logo: 'https://media.api-sports.io/football/teams/532.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 20,
          team: {
            id: 533,
            name: 'Villarreal',
            logo: 'https://media.api-sports.io/football/teams/533.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'ECL Playoffs',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
      ],
      [
        {
          rank: 1,
          team: {
            id: 533,
            name: 'Villarreal',
            logo: 'https://media.api-sports.io/football/teams/533.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'ECL Playoffs',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 2,
          team: {
            id: 797,
            name: 'Elche',
            logo: 'https://media.api-sports.io/football/teams/797.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 3,
          team: {
            id: 542,
            name: 'Alaves',
            logo: 'https://media.api-sports.io/football/teams/542.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 4,
          team: {
            id: 531,
            name: 'Athletic Club',
            logo: 'https://media.api-sports.io/football/teams/531.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 5,
          team: {
            id: 530,
            name: 'Atletico Madrid',
            logo: 'https://media.api-sports.io/football/teams/530.png',
          },
          points: 3,
          goalsDiff: 2,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 6,
          team: {
            id: 529,
            name: 'Barcelona',
            logo: 'https://media.api-sports.io/football/teams/529.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 7,
          team: {
            id: 538,
            name: 'Celta Vigo',
            logo: 'https://media.api-sports.io/football/teams/538.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 8,
          team: {
            id: 544,
            name: 'Deportivo La Coruna',
            logo: 'https://media.api-sports.io/football/teams/544.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 1,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 9,
          team: {
            id: 540,
            name: 'Espanyol',
            logo: 'https://media.api-sports.io/football/teams/540.png',
          },
          points: 3,
          goalsDiff: 3,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 3,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 10,
          team: {
            id: 727,
            name: 'Osasuna',
            logo: 'https://media.api-sports.io/football/teams/727.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 11,
          team: {
            id: 4665,
            name: 'Racing Santander',
            logo: 'https://media.api-sports.io/football/teams/4665.png',
          },
          points: 1,
          goalsDiff: 0,
          group: 'La Liga',
          form: 'D',
          status: 'same',
          description: 'Europa League league stage',
          all: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          home: {
            played: 1,
            win: 0,
            draw: 1,
            lose: 0,
            goals: {
              for: 2,
              against: 2,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 12,
          team: {
            id: 543,
            name: 'Real Betis',
            logo: 'https://media.api-sports.io/football/teams/543.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 13,
          team: {
            id: 541,
            name: 'Real Madrid',
            logo: 'https://media.api-sports.io/football/teams/541.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 14,
          team: {
            id: 548,
            name: 'Real Sociedad',
            logo: 'https://media.api-sports.io/football/teams/548.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 15,
          team: {
            id: 536,
            name: 'Sevilla',
            logo: 'https://media.api-sports.io/football/teams/536.png',
          },
          points: 3,
          goalsDiff: 1,
          group: 'La Liga',
          form: 'W',
          status: 'same',
          description: 'Champions League league stage',
          all: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          home: {
            played: 1,
            win: 1,
            draw: 0,
            lose: 0,
            goals: {
              for: 2,
              against: 1,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 16,
          team: {
            id: 532,
            name: 'Valencia',
            logo: 'https://media.api-sports.io/football/teams/532.png',
          },
          points: 0,
          goalsDiff: 0,
          group: 'La Liga',
          form: null,
          status: 'same',
          description: null,
          all: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 17,
          team: {
            id: 728,
            name: 'Rayo Vallecano',
            logo: 'https://media.api-sports.io/football/teams/728.png',
          },
          points: 0,
          goalsDiff: -1,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: null,
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 1,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 18,
          team: {
            id: 535,
            name: 'Malaga',
            logo: 'https://media.api-sports.io/football/teams/535.png',
          },
          points: 0,
          goalsDiff: -2,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 2,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 19,
          team: {
            id: 546,
            name: 'Getafe',
            logo: 'https://media.api-sports.io/football/teams/546.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
        {
          rank: 20,
          team: {
            id: 539,
            name: 'Levante',
            logo: 'https://media.api-sports.io/football/teams/539.png',
          },
          points: 0,
          goalsDiff: -3,
          group: 'La Liga',
          form: 'L',
          status: 'same',
          description: 'Relegation',
          all: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          home: {
            played: 0,
            win: 0,
            draw: 0,
            lose: 0,
            goals: {
              for: 0,
              against: 0,
            },
          },
          away: {
            played: 1,
            win: 0,
            draw: 0,
            lose: 1,
            goals: {
              for: 0,
              against: 3,
            },
          },
          update: '2026-08-20T00:00:00+00:00',
        },
      ],
    ],
  },
  createdAt: new Date('2026-08-20T09:51:18.422Z'),
  updatedAt: new Date('2026-08-20T09:51:18.422Z'),
};
