name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml
    secrets:
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}

  sonarcloud:
    name: Analyze Code with SonarCloud
    needs: tests
    if: ${{ vars.SONAR_ORGANIZATION != '' && vars.SONAR_PROJECT_KEY != '' }}
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
